i = input('Digite algo:')
print('O tipo primeitivo é ', type(i))
print('O que você gigitou é apenas espaços', i.isspace())
print('O que você digitou é numerico?', i.isnumeric())
print('O que você digitou é apenas letra?', i.isalpha())
print('O que você digitou está em letras maiusculas?', i.isupper())
print('O que você digitou é alfanumerico?', i.isalnum())
print("O que voce digitou esta em letras minusculas?", i.islower())
print('O que você digitou esta capitalizado?', i.istitle() )